### ISSUE TITLE
#server-log enhancement

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#146]
It would be good to have the log display when a user has been banned. Right now, it just shows them leaving the guild, but having a different message would be ideal:

🔨 `[00:00:00]` **Cole#0001** has been banned from the guild. Total members: **000 000**

**Comment by ThePjpollie** [comment]
It'll be both messages then since the event trigger we use does not detect bans or not. Only thing it sees is that it leaves. So on the moment you do `!ban` I'll send the message in the logs channel but the other message will stay. 

If you'll be doing ban through the Discord UI then there is almost no way for us to detect ¯\\_(ツ)\_/¯

**Comment by coledeb** [comment]
Thats weird, the only reason that I suggested it is because utilibot was able to detect it and thats how it sent the messages in the log channel.
