### ISSUE TITLE
Music channel & functionality

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#88]
@ThePjpollie I would love for the music functionality that was in JHZER's server to make its way to AC basically exactly the same it was if possible. Crazy good implementation. Could you explain to me how (if it existed) the channel was moderated? Any mod `!skip` commands or the like?

**Comment by HaydenMeloche** [comment]
i'd rather just keep pollies bot with music in rather than copy it over.
Thoughts @coledeb @ThePjpollie ?

**Comment by ThePjpollie** [comment]
With pleasure! Then I can work on 1 bot to improve it. And no need to make it on mine and copy over and transform to yours. Also I did this because restarting bot = bot down. So if you wanna update the current AlphaConsole bot you need to keep track is someone using it and need to wait then (That's what I had on JHZER's bot) and I can tell you that's annoying as f*ck. So it also helps development for AlphaConsole
